name = "camera-simulator"
compatibility_date = "2024-09-23"
account_id = "a2ac61f5f73089be223a143af71ad7d4"

[assets]
directory = "./"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
